/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import {
  Route as AuthImport,
  Route as AuthLoginImport,
  Route as IndexImport,
} from './routes/_auth';
import { Route as AuthForgetPasswordImport } from './routes/_auth/forget-password';
import { Route as AuthRegisterImport } from './routes/_auth/register';
import { Route as DashboardImport } from './routes/_dashboard';
import { Route as DashboardHomeImport } from './routes/_dashboard/home';
import { Route as DashboardTeachersImport } from './routes/_dashboard/teachers';

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const DashboardTeachersRoute = DashboardTeachersImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardRoute,
} as any);

const DashboardHomeRoute = DashboardHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any);

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any);

const AuthForgetPasswordRoute = AuthForgetPasswordImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => AuthRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/_dashboard': {
      id: '/_dashboard';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/forget-password': {
      id: '/_auth/forget-password';
      path: '/forget-password';
      fullPath: '/forget-password';
      preLoaderRoute: typeof AuthForgetPasswordImport;
      parentRoute: typeof AuthImport;
    };
    '/_auth/login': {
      id: '/_auth/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof AuthImport;
    };
    '/_auth/register': {
      id: '/_auth/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof AuthRegisterImport;
      parentRoute: typeof AuthImport;
    };
    '/_dashboard/home': {
      id: '/_dashboard/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof DashboardHomeImport;
      parentRoute: typeof DashboardImport;
    };
    '/_dashboard/teachers': {
      id: '/_dashboard/teachers';
      path: '/teachers';
      fullPath: '/teachers';
      preLoaderRoute: typeof DashboardTeachersImport;
      parentRoute: typeof DashboardImport;
    };
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface DashboardRouteChildren {
  DashboardHomeRoute: typeof DashboardHomeRoute;
  DashboardTeachersRoute: typeof DashboardTeachersRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardTeachersRoute: DashboardTeachersRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren
);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '': typeof DashboardRouteWithChildren;
  '/forget-password': typeof AuthForgetPasswordRoute;
  '/login': typeof AuthLoginRoute;
  '/register': typeof AuthRegisterRoute;
  '/home': typeof DashboardHomeRoute;
  '/teachers': typeof DashboardTeachersRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '': typeof DashboardRouteWithChildren;
  '/forget-password': typeof AuthForgetPasswordRoute;
  '/login': typeof AuthLoginRoute;
  '/register': typeof AuthRegisterRoute;
  '/home': typeof DashboardHomeRoute;
  '/teachers': typeof DashboardTeachersRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/_dashboard': typeof DashboardRouteWithChildren;
  '/_auth/forget-password': typeof AuthForgetPasswordRoute;
  '/_auth/login': typeof AuthLoginRoute;
  '/_auth/register': typeof AuthRegisterRoute;
  '/_dashboard/home': typeof DashboardHomeRoute;
  '/_dashboard/teachers': typeof DashboardTeachersRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | ''
    | '/forget-password'
    | '/login'
    | '/register'
    | '/home'
    | '/teachers';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | ''
    | '/forget-password'
    | '/login'
    | '/register'
    | '/home'
    | '/teachers';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forget-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_dashboard/home'
    | '/_dashboard/teachers';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  DashboardRoute: typeof DashboardRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/forget-password",
        "/_auth/login",
        "/_auth/register"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/home",
        "/_dashboard/teachers"
      ]
    },
    "/_auth/forget-password": {
      "filePath": "_auth/forget-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_dashboard/home": {
      "filePath": "_dashboard/home.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/teachers": {
      "filePath": "_dashboard/teachers.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
